name: Deploy Client Production

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'npm'
      - name: Create .env file
        run: |
          cat <<EOF > .env
          ${{ secrets.ENV }}
          EOF
      
      - name: Install dependencies
        run: npm install --force

      - name: Build app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            set -e
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/cims-ttp-client

            git fetch --all
            git reset --hard origin/master
            cat <<EOF > .env
            ${{ secrets.ENV }}
            EOF
            echo "Content of .env:"
            cat .env

            echo "→ Install dependencies"
            npm install --force

            echo "→ Build app"
            npm run build
            
            echo "→ Restart Pm2"
            pm2 restart cims-ttp-client